combine_control_expr = false
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
force_multiline_blocks = true
format_code_in_doc_comments = true
hex_literal_case = "Upper"
match_block_trailing_comma = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
struct_field_align_threshold = 20
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
